name: buildsln-ubuntu-cache

on:
  push:
    branches:
    - '*'

jobs:
  buildsln:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      	  cache: true
          cache-dependency-path: "**/packages.lock.json"
      - run: dotnet restore --locked-mode 
      - run: dotnet build bitwarden-server.sln


