name: Testing

on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Retrieve secrets
        id: retrieve-secrets
        uses: bitwarden/gh-actions/get-keyvault-secrets-3@vgrassia/test
        with:
          creds: ${{ secrets.AZURE_KV_CI_SERVICE_PRINCIPAL }}
          keyvault: "bitwarden-ci"
          secrets: "test-secret-1,
                    test-secret-2,
                    test-secret-3"